FROM osrf/ros:humble-core

# complete the docker file
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    ros-humble-cv-bridge \
    ros-humble-image-transport \
    ros-humble-rclcpp \
    ros-humble-std-msgs \
    libopencv-dev